# Generated by Django 3.1.3 on 2020-11-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='productname',
            field=models.TextField(default='productname'),
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.TextField(default='site'),
        ),
    ]
