# Generated by Django 3.1.3 on 2020-11-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201121_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_m',
            field=models.TextField(default='category_m'),
        ),
    ]
