# Generated by Django 3.1.3 on 2020-11-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(default='color'),
        ),
        migrations.AddField(
            model_name='product',
            name='producttype',
            field=models.TextField(default='상품구분'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.TextField(default='별점'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.TextField(default='season'),
        ),
        migrations.AddField(
            model_name='product',
            name='style_m',
            field=models.TextField(default='style'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_m',
            field=models.TextField(default='카테고리'),
        ),
    ]
